version: 0.0
os: linux
files:
  - source: /*
    destination: /var/www/magento-new-build/
hooks:
  BeforeInstall:
    - location: scripts/restart_service
    - location: scripts/install_dependencies
      timeout: 1200
      runas: root  
  AfterInstall:
    - location: scripts/run_process
      timeout: 1200
      runas: root
